FROM node:22-alpine AS base
WORKDIR /app

ARG NODE_ENV=production
ARG DATABASE_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG REDIS_URL
ARG TRACKING_SALT
ARG ENCRYPTION_KEY
ARG WEBHOOK_SIGNING_SECRET
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_URL
ARG OPENAI_API_KEY
ARG OPENAI_MODEL
ARG META_APP_ID
ARG META_APP_SECRET
ARG META_REDIRECT_URI
ARG META_GRAPH_VERSION
ARG TRACKING_MODE
ARG DEV_HARDCODE_USER_EMAIL
ARG DEV_HARDCODE_USER_PASSWORD
ARG DEV_HARDCODE_USER_NAME

COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

ENV NODE_ENV=$NODE_ENV \
    DATABASE_URL=$DATABASE_URL \
    NEXTAUTH_URL=$NEXTAUTH_URL \
    NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
    REDIS_URL=$REDIS_URL \
    TRACKING_SALT=$TRACKING_SALT \
    ENCRYPTION_KEY=$ENCRYPTION_KEY \
    WEBHOOK_SIGNING_SECRET=$WEBHOOK_SIGNING_SECRET \
    NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    OPENAI_API_KEY=$OPENAI_API_KEY \
    OPENAI_MODEL=$OPENAI_MODEL \
    META_APP_ID=$META_APP_ID \
    META_APP_SECRET=$META_APP_SECRET \
    META_REDIRECT_URI=$META_REDIRECT_URI \
    META_GRAPH_VERSION=$META_GRAPH_VERSION \
    TRACKING_MODE=$TRACKING_MODE \
    DEV_HARDCODE_USER_EMAIL=$DEV_HARDCODE_USER_EMAIL \
    DEV_HARDCODE_USER_PASSWORD=$DEV_HARDCODE_USER_PASSWORD \
    DEV_HARDCODE_USER_NAME=$DEV_HARDCODE_USER_NAME

COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
